# Clock signal
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]

#Buttons
set_property PACKAGE_PIN W19 [get_ports lb]						
	set_property IOSTANDARD LVCMOS33 [get_ports lb]
set_property PACKAGE_PIN T17 [get_ports rb]						
	set_property IOSTANDARD LVCMOS33 [get_ports rb]
	
#led	
set_property PACKAGE_PIN U16 [get_ports {rf_we}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {rf_we}]

#7 segment display
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

set_property PACKAGE_PIN V7 [get_ports dp]							
	set_property IOSTANDARD LVCMOS33 [get_ports dp]

set_property PACKAGE_PIN U2 [get_ports {an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[0]}]
set_property PACKAGE_PIN U4 [get_ports {an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[1]}]
set_property PACKAGE_PIN V4 [get_ports {an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[2]}]
set_property PACKAGE_PIN W4 [get_ports {an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {an[3]}] 
	
	
# Switches
set_property PACKAGE_PIN V17 [get_ports {extinstruction[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[0]}]
set_property PACKAGE_PIN V16 [get_ports {extinstruction[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[1]}]
set_property PACKAGE_PIN W16 [get_ports {extinstruction[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[2]}]
set_property PACKAGE_PIN W17 [get_ports {extinstruction[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[3]}]
set_property PACKAGE_PIN W15 [get_ports {extinstruction[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[4]}]
set_property PACKAGE_PIN V15 [get_ports {extinstruction[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[5]}]
set_property PACKAGE_PIN W14 [get_ports {extinstruction[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[6]}]
set_property PACKAGE_PIN W13 [get_ports {extinstruction[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[7]}]
set_property PACKAGE_PIN V2 [get_ports {extinstruction[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[8]}]
set_property PACKAGE_PIN T3 [get_ports {extinstruction[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[9]}]
set_property PACKAGE_PIN T2 [get_ports {extinstruction[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[10]}]
set_property PACKAGE_PIN R3 [get_ports {extinstruction[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {extinstruction[11]}]
set_property PACKAGE_PIN R2 [get_ports reset]					
	set_property IOSTANDARD LVCMOS33 [get_ports reset]